packageExtensions:
  jest-environment-puppeteer@*:
    dependencies:
      jest-environment-node: ^26.2.0
      puppeteer: ^5.2.1
  jest-util@*:
    dependencies:
      jest-runner: ^27.0.1
  jest-circus@*:
    dependencies:
      slash: ^3.0.0

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: "@yarnpkg/plugin-constraints"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-stage.cjs
    spec: "@yarnpkg/plugin-stage"

yarnPath: .yarn/releases/yarn-3.0.0-rc.2.cjs
