compressionLevel: mixed

enableGlobalCache: false

nodeLinker: pnp

packageExtensions:
  "@storybook/addon-docs@*":
    dependencies:
      "@babel/core": "*"
  "@storybook/addon-interactions@*":
    dependencies:
      core-js: "*"
  "@storybook/instrumenter@*":
    dependencies:
      core-js: "*"
  prosemirror-collab@*:
    dependencies:
      prosemirror-transform: "*"
  prosemirror-gapcursor@*:
    dependencies:
      prosemirror-transform: "*"
  prosemirror-inputrules@*:
    dependencies:
      prosemirror-model: "*"
  prosemirror-keymap@*:
    dependencies:
      prosemirror-view: "*"
  prosemirror-schema-list@*:
    dependencies:
      orderedmap: "*"
  prosemirror-state@*:
    dependencies:
      prosemirror-view: "*"

pnpMode: strict

supportedArchitectures:
  cpu:
    - x64
    - arm64
  libc:
    - current
    - glibc
  os:
    - darwin
    - linux

yarnPath: .yarn/releases/yarn-4.0.0.cjs
