[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"

[build]
  publish = "app/app-root/dist"
  command = "pnpm build" 

[build.environment]
  NODE_VERSION = "lts/*"
