packages:
  - 'packages/app-bundler/*'
  - 'packages/app-window/*'
  - 'packages/app-worker/*'
  - 'packages/e2e-tests/*'
  - 'packages/js-lib/*'
  - 'packages/lib/*'
  - 'packages/shared/*'
  - 'packages/test-utils/*'
  - 'packages/tooling/*'
