export const CORE_ACTIONS_CREATE_NATIVE_FS_WORKSPACE =
  'action::bangle-io-core-actions:CREATE_NATIVE_FS_WORKSPACE_ACTION';

export const CORE_ACTIONS_CREATE_BROWSER_WORKSPACE =
  'action::bangle-io-core-actions:CREATE_BROWSER_WORKSPACE_ACTION';

export const CORE_ACTIONS_SERVICE_WORKER_RELOAD =
  'action::bangle-io-core-actions:CORE_ACTIONS_SERVICE_WORKER_RELOAD_ACTION';
export const CORE_ACTIONS_SERVICE_WORKER_DISMISS_UPDATE =
  'action::bangle-io-core-actions:CORE_ACTIONS_SERVICE_WORKER_DISMISS_UPDATE_ACTION';
