export enum AppDatabaseErrorCode {
  WORKSPACE_NOT_FOUND = 'WORKSPACE_NOT_FOUND',
  WORKSPACE_EXISTS = 'WORKSPACE_EXISTS',
  WORKSPACE_ERROR = 'WORKSPACE_ERROR',

  MISC_DATA_ERROR = 'MISC_DATA_ERROR',

  ENTRY_ALREADY_EXISTS = 'ENTRY_ALREADY_EXISTS',
  ENTRY_NOT_FOUND = 'ENTRY_NOT_FOUND',
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
}
