export enum AppDatabaseErrorCode {
  WORKSPACE_NOT_FOUND = 'WORKSPACE_NOT_FOUND',
  WORKSPACE_EXISTS = 'WORKSPACE_EXISTS',
  WORKSPACE_ERROR = 'WORKSPACE_ERROR',

  MISC_DATA_ERROR = 'MISC_DATA_ERROR',
}
