import { colors } from '../theme/colors';

describe('theme-colors', () => {
  test('colors', () => {
    expect(colors).toMatchInlineSnapshot(`
      {
        "appActivitybarBgColor": "var(--BV-app-activitybar-bgColor)",
        "appEditorBgColor": "var(--BV-app-editor-bgColor)",
        "bgBody": "var(--BV-color-background-body)",
        "bgBrand": "var(--BV-color-background-brand)",
        "bgBrandAccent": "var(--BV-color-background-brandAccent)",
        "bgBrandAccentActive": "var(--BV-color-background-brandAccentActive)",
        "bgBrandAccentHover": "var(--BV-color-background-brandAccentHover)",
        "bgBrandAccentLight": "var(--BV-color-background-brandAccentLight)",
        "bgBrandAccentLightActive": "var(--BV-color-background-brandAccentLightActive)",
        "bgBrandAccentLightHover": "var(--BV-color-background-brandAccentLightHover)",
        "bgCaution": "var(--BV-color-background-caution)",
        "bgCautionActive": "var(--BV-color-background-cautionActive)",
        "bgCautionHover": "var(--BV-color-background-cautionHover)",
        "bgCautionLight": "var(--BV-color-background-cautionLight)",
        "bgCautionLightActive": "var(--BV-color-background-cautionLightActive)",
        "bgCautionLightHover": "var(--BV-color-background-cautionLightHover)",
        "bgCritical": "var(--BV-color-background-critical)",
        "bgCriticalActive": "var(--BV-color-background-criticalActive)",
        "bgCriticalHover": "var(--BV-color-background-criticalHover)",
        "bgCriticalLight": "var(--BV-color-background-criticalLight)",
        "bgCriticalLightActive": "var(--BV-color-background-criticalLightActive)",
        "bgCriticalLightHover": "var(--BV-color-background-criticalLightHover)",
        "bgInfo": "var(--BV-color-background-info)",
        "bgInfoActive": "var(--BV-color-background-infoActive)",
        "bgInfoHover": "var(--BV-color-background-infoHover)",
        "bgInfoLight": "var(--BV-color-background-infoLight)",
        "bgInfoLightActive": "var(--BV-color-background-infoLightActive)",
        "bgInfoLightHover": "var(--BV-color-background-infoLightHover)",
        "bgNeutral": "var(--BV-color-background-neutral)",
        "bgNeutralActive": "var(--BV-color-background-neutralActive)",
        "bgNeutralHover": "var(--BV-color-background-neutralHover)",
        "bgNeutralLight": "var(--BV-color-background-neutralLight)",
        "bgNeutralLightActive": "var(--BV-color-background-neutralLightActive)",
        "bgNeutralLightHover": "var(--BV-color-background-neutralLightHover)",
        "bgNeutralSoft": "var(--BV-color-background-neutralSoft)",
        "bgPositive": "var(--BV-color-background-positive)",
        "bgPositiveActive": "var(--BV-color-background-positiveActive)",
        "bgPositiveHover": "var(--BV-color-background-positiveHover)",
        "bgPositiveLight": "var(--BV-color-background-positiveLight)",
        "bgPositiveLightActive": "var(--BV-color-background-positiveLightActive)",
        "bgPositiveLightHover": "var(--BV-color-background-positiveLightHover)",
        "bgSurface": "var(--BV-color-background-surface)",
        "bgSurfaceDark": "var(--BV-color-background-surfaceDark)",
        "fgBrandAccent": "var(--BV-color-foreground-brandAccent)",
        "fgBrandAccentLight": "var(--BV-color-foreground-brandAccentLight)",
        "fgCaution": "var(--BV-color-foreground-caution)",
        "fgCautionLight": "var(--BV-color-foreground-cautionLight)",
        "fgCritical": "var(--BV-color-foreground-critical)",
        "fgCriticalLight": "var(--BV-color-foreground-criticalLight)",
        "fgInfo": "var(--BV-color-foreground-info)",
        "fgInfoLight": "var(--BV-color-foreground-infoLight)",
        "fgLink": "var(--BV-color-foreground-link)",
        "fgLinkHover": "var(--BV-color-foreground-linkHover)",
        "fgLinkLight": "var(--BV-color-foreground-linkLight)",
        "fgLinkVisited": "var(--BV-color-foreground-linkVisited)",
        "fgNeutral": "var(--BV-color-foreground-neutral)",
        "fgNeutralInverted": "var(--BV-color-foreground-neutralInverted)",
        "fgNeutralLight": "var(--BV-color-foreground-neutralLight)",
        "fgPositive": "var(--BV-color-foreground-positive)",
        "fgPositiveLight": "var(--BV-color-foreground-positiveLight)",
        "fgPrimary": "var(--BV-color-foreground-primary)",
        "fgPrimaryInverted": "var(--BV-color-foreground-primaryInverted)",
        "fgPrimaryLight": "var(--BV-color-foreground-primaryLight)",
        "fgPromote": "var(--BV-color-foreground-promote)",
        "fgPromoteLight": "var(--BV-color-foreground-promoteLight)",
        "fgSecondary": "var(--BV-color-foreground-secondary)",
        "fgSecondaryInverted": "var(--BV-color-foreground-secondaryInverted)",
        "fgSecondaryLight": "var(--BV-color-foreground-secondaryLight)",
      }
    `);
  });
});
