import { colors } from '../theme/colors';

describe('theme-colors', () => {
  test('colors', () => {
    expect(colors).toMatchInlineSnapshot(`
      {
        "colorActivitybarBg": "var(--BV-app-activitybar-color-bg)",
        "colorBg": "var(--BV-color-neutral-bg)",
        "colorBgLayer1": "var(--BV-color-neutral-bgLayer1)",
        "colorBgLayer2": "var(--BV-color-neutral-bgLayer2)",
        "colorBorder": "var(--BV-color-neutral-border)",
        "colorBorderDark": "var(--BV-color-neutral-borderDark)",
        "colorBorderDarker": "var(--BV-color-neutral-borderDarker)",
        "colorBorderLight": "var(--BV-color-neutral-borderLight)",
        "colorBtn": "var(--BV-color-neutral-btn)",
        "colorBtnColor": "var(--BV-color-neutral-btnColor)",
        "colorBtnDisabled": "var(--BV-color-neutral-btnDisabled)",
        "colorBtnDown": "var(--BV-color-neutral-btnDown)",
        "colorBtnHover": "var(--BV-color-neutral-btnHover)",
        "colorCautionBorder": "var(--BV-color-caution-border)",
        "colorCautionBorderDark": "var(--BV-color-caution-borderDark)",
        "colorCautionBorderDarker": "var(--BV-color-caution-borderDarker)",
        "colorCautionBorderLight": "var(--BV-color-caution-borderLight)",
        "colorCautionBtn": "var(--BV-color-caution-btn)",
        "colorCautionBtnColor": "var(--BV-color-caution-btnColor)",
        "colorCautionBtnDisabled": "var(--BV-color-caution-btnDisabled)",
        "colorCautionBtnDown": "var(--BV-color-caution-btnDown)",
        "colorCautionBtnHover": "var(--BV-color-caution-btnHover)",
        "colorCautionIcon": "var(--BV-color-caution-icon)",
        "colorCautionIconDisabled": "var(--BV-color-caution-iconDisabled)",
        "colorCautionIconLight": "var(--BV-color-caution-iconLight)",
        "colorCriticalBorder": "var(--BV-color-critical-border)",
        "colorCriticalBorderDark": "var(--BV-color-critical-borderDark)",
        "colorCriticalBorderDarker": "var(--BV-color-critical-borderDarker)",
        "colorCriticalBorderLight": "var(--BV-color-critical-borderLight)",
        "colorCriticalBtn": "var(--BV-color-critical-btn)",
        "colorCriticalBtnColor": "var(--BV-color-critical-btnColor)",
        "colorCriticalBtnDisabled": "var(--BV-color-critical-btnDisabled)",
        "colorCriticalBtnDown": "var(--BV-color-critical-btnDown)",
        "colorCriticalBtnHover": "var(--BV-color-critical-btnHover)",
        "colorCriticalIcon": "var(--BV-color-critical-icon)",
        "colorCriticalIconDisabled": "var(--BV-color-critical-iconDisabled)",
        "colorCriticalIconLight": "var(--BV-color-critical-iconLight)",
        "colorEditorBg": "var(--BV-app-editor-color-bg)",
        "colorIcon": "var(--BV-color-neutral-icon)",
        "colorIconDisabled": "var(--BV-color-neutral-iconDisabled)",
        "colorIconLight": "var(--BV-color-neutral-iconLight)",
        "colorNeutralBg": "var(--BV-color-neutral-bg)",
        "colorNeutralBgLayer1": "var(--BV-color-neutral-bgLayer1)",
        "colorNeutralBgLayer2": "var(--BV-color-neutral-bgLayer2)",
        "colorNeutralBorder": "var(--BV-color-neutral-border)",
        "colorNeutralBorderDark": "var(--BV-color-neutral-borderDark)",
        "colorNeutralBorderDarker": "var(--BV-color-neutral-borderDarker)",
        "colorNeutralBorderLight": "var(--BV-color-neutral-borderLight)",
        "colorNeutralBtn": "var(--BV-color-neutral-btn)",
        "colorNeutralBtnColor": "var(--BV-color-neutral-btnColor)",
        "colorNeutralBtnDisabled": "var(--BV-color-neutral-btnDisabled)",
        "colorNeutralBtnDown": "var(--BV-color-neutral-btnDown)",
        "colorNeutralBtnHover": "var(--BV-color-neutral-btnHover)",
        "colorNeutralIcon": "var(--BV-color-neutral-icon)",
        "colorNeutralIconDisabled": "var(--BV-color-neutral-iconDisabled)",
        "colorNeutralIconLight": "var(--BV-color-neutral-iconLight)",
        "colorNeutralText": "var(--BV-color-neutral-text)",
        "colorNeutralTextDark": "var(--BV-color-neutral-textDark)",
        "colorNeutralTextDisabled": "var(--BV-color-neutral-textDisabled)",
        "colorNeutralTextInverted": "var(--BV-color-neutral-textInverted)",
        "colorNeutralTextLight": "var(--BV-color-neutral-textLight)",
        "colorPositiveBorder": "var(--BV-color-positive-border)",
        "colorPositiveBorderDark": "var(--BV-color-positive-borderDark)",
        "colorPositiveBorderDarker": "var(--BV-color-positive-borderDarker)",
        "colorPositiveBorderLight": "var(--BV-color-positive-borderLight)",
        "colorPositiveBtn": "var(--BV-color-positive-btn)",
        "colorPositiveBtnColor": "var(--BV-color-positive-btnColor)",
        "colorPositiveBtnDisabled": "var(--BV-color-positive-btnDisabled)",
        "colorPositiveBtnDown": "var(--BV-color-positive-btnDown)",
        "colorPositiveBtnHover": "var(--BV-color-positive-btnHover)",
        "colorPositiveIcon": "var(--BV-color-positive-icon)",
        "colorPositiveIconDisabled": "var(--BV-color-positive-iconDisabled)",
        "colorPositiveIconLight": "var(--BV-color-positive-iconLight)",
        "colorPromoteBorder": "var(--BV-color-promote-border)",
        "colorPromoteBorderDark": "var(--BV-color-promote-borderDark)",
        "colorPromoteBorderDarker": "var(--BV-color-promote-borderDarker)",
        "colorPromoteBorderLight": "var(--BV-color-promote-borderLight)",
        "colorPromoteBtn": "var(--BV-color-promote-btn)",
        "colorPromoteBtnColor": "var(--BV-color-promote-btnColor)",
        "colorPromoteBtnDisabled": "var(--BV-color-promote-btnDisabled)",
        "colorPromoteBtnDown": "var(--BV-color-promote-btnDown)",
        "colorPromoteBtnHover": "var(--BV-color-promote-btnHover)",
        "colorPromoteIcon": "var(--BV-color-promote-icon)",
        "colorPromoteIconDisabled": "var(--BV-color-promote-iconDisabled)",
        "colorPromoteIconLight": "var(--BV-color-promote-iconLight)",
        "colorText": "var(--BV-color-neutral-text)",
        "colorTextDark": "var(--BV-color-neutral-textDark)",
        "colorTextDisabled": "var(--BV-color-neutral-textDisabled)",
        "colorTextInverted": "var(--BV-color-neutral-textInverted)",
        "colorTextLight": "var(--BV-color-neutral-textLight)",
      }
    `);
  });
});
