export const INVALID_GITHUB_TOKEN = 'INVALID_GITHUB_TOKEN';
export const GITHUB_API_ERROR = 'GITHUB_API_ERROR';
export const FILE_ALREADY_DELETED = 'FILE_ALREADY_DELETED';
export const FILE_DELETED = 'FILE_DELETED';
export const FILE_DOES_NOT_EXIST = 'FILE_DOES_NOT_EXIST';
export const FILE_ALREADY_EXISTS_ERROR = 'FILE_ALREADY_EXISTS_ERROR';

export const GITHUB_FILE_NOT_FOUND_ERROR = 'GITHUB_FILE_NOT_FOUND_ERROR';
export const INVALID_GITHUB_CONFIGURATION = 'INVALID_GITHUB_CONFIGURATION';
export const INVALID_GITHUB_RESPONSE = 'INVALID_GITHUB_RESPONSE';
export const INVALID_GITHUB_FILE_FORMAT = 'INVALID_GITHUB_FILE_FORMAT';
export const GITHUB_NOT_SUPPORTED = 'NOT_SUPPORTED';

export type ErrorCodesType =
  | typeof INVALID_GITHUB_TOKEN
  | typeof INVALID_GITHUB_CONFIGURATION
  | typeof INVALID_GITHUB_RESPONSE
  | typeof INVALID_GITHUB_FILE_FORMAT
  | typeof GITHUB_API_ERROR
  | typeof GITHUB_FILE_NOT_FOUND_ERROR
  | typeof GITHUB_NOT_SUPPORTED
  | typeof FILE_ALREADY_DELETED
  | typeof FILE_DELETED
  | typeof FILE_ALREADY_EXISTS_ERROR;
