export const VALIDATION_ERROR = 'VALIDATION_ERROR';
export const FILE_NOT_FOUND_ERROR = 'FILE_NOT_FOUND_ERROR';
export const UPSTREAM_ERROR = 'UPSTREAM_ERROR';
export const FILE_ALREADY_EXISTS_ERROR = 'FILE_ALREADY_EXISTS_ERROR';
export const NOT_A_DIRECTORY_ERROR = 'NOT_A_DIRECTORY_ERROR';
export const NATIVE_BROWSER_PERMISSION_ERROR =
  'NATIVE_BROWSER_PERMISSION_ERROR';
