import './Dialog/style.css';
import './ErrorBoundary.css';
import './Icons.css';
import './InlinePaletteUI/InlinePaletteUI.css';
import './Input/Input.css';
import './misc.css';
import './PrettyKeybinding.css';
import './Sidebar/Sidebar.css';
import './UniversalPalette/UniversalPalette.css';
