import '@bangle.io/shared/extensions-style';
import '@bangle.io/style/style';
import '@bangle.io/ui-components/style';
import '@bangle.io/ui-bangle-button/style';
// layout
import '@bangle.io/activitybar/style';
import '@bangle.io/workspace-sidebar/style';
import '@bangle.io/editor-container/style';
import '@bangle.io/note-sidebar/style';
import './onboarding-modal/style.css';
