# .github/workflows/chromatic.yml

# Workflow name
name: 'Chromatic'

concurrency:
  group: bangle-chromatic-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
# 👇 Workflow event to trigger execution
on:
  push:
    branches-ignore:
      - 'production'
      - 'staging'

jobs:
  chromatic-deployment:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v1
      - name: yarn install
        run: yarn install --immutable --immutable-cache
        # 👇 Adds Chromatic as a step in the workflow
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        # Chromatic GitHub Action options
        with:
          # 👇 Chromatic projectToken, refer to the manage page to obtain it.
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: tooling/storybook
          debug: true
