name: Create diagram
on:
  workflow_dispatch: {}
  push:
    branches:
      - dev
jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Update diagram
        uses: githubocto/repo-visualizer@main
        with:
          excluded_paths: 'ignore,.github,.yarn,.husky,.vscode,build,node_modules'
